### ISSUE TITLE
Create a release workflow

### ISSUE THREAD

**Issue by jonearley** [mlibrary/design-system#12]
Related reading:
https://github.com/gulpjs/gulp/blob/master/docs/recipes/automate-release-workflow.md
https://medium.com/slalom-engineering/chasing-the-holy-grail-bbc0b7cce365
https://unpkg.com/#/. This is how http://tachyons.io/ is hosted.

- [ ] Add release process functionality through Gulp
- [ ] Add download button (min css)

**Comment by bridgetburke** [comment]
That Medium article was really helpful.

**Comment by jonearley** [comment]
Workflow created. Content added to the repo readme about how to use the workflow.
