### ISSUE TITLE
Decide on CSS naming conventions 

### ISSUE THREAD

**Issue by bridgetburke** [mlibrary/design-system#5]
Naming should not get in the way of productivity.

- BEM
- SMACSS
- Functional CSS
- Atomic CSS
- OOCSS

Anything else?

**Comment by bridgetburke** [comment]
I've been thinking a lot about a/our CSS page and moving forward. 

Many thoughts below based on reading a [good article on using BEM + SMACSS](https://webuild.envato.com/blog/how-to-scale-and-maintain-legacy-css-with-sass-and-smacss/) with different workflow/existing codebases. The article is from Envato (2013). [Their system is called "Style".](https://github.com/bensmithett/style). Modified SMACSS with [BEVM](https://webuild.envato.com/blog/chainable-bem-modifiers/). 

**Goal: To move forward, let's begin with a modified SMACSS + BEM.**

**Methodology: The component paradigm...**
SMACSS:
Maybe instead of Base, Layout, Module, State, Theme --> Using Base, Module, State
Base: resets, base style, utilities
Module: Everything else
State: state :) (Global state classes are in the Base)

I like lowering the complication of layout + module by removing one and making everything a "module". Or "Component".

**Syntax:**
[BEM](https://en.bem.info/methodology/key-concepts/)
[SUIT CSS](https://github.com/suitcss/suit)

Naming: where is the architectural division? Between **Utilities** and **Components**. 

Utilities are low-level, structural, and positional. They may have a preface to indicate, such as `u-padding-none`. Utilities are used frequently and allow for reduction of code and consistency. Utilities can be added to any element and can be used together and along with component classes.

Components: This is where we run with the BEM-ish naming.

**What syntax do you prefer?**
Jon:
Bridget: Preferred: meaningful hyphens, not camelCase (as in SUITS).
`<button class="button button--default"></button>`
I like BEM but it's so strict, my punk rock side won't allow me to be so strict so a modified BEM? Willing to talk it out :)

**Action items**
- [ ] Create a CSS page

**Comment by jonearley** [comment]
I support this and believe it's something we will need to release v1.

**Comment by jonearley** [comment]
Are you thinking the CSS page would be a style guide format? Such as: https://github.com/airbnb/css?

**Comment by bridgetburke** [comment]
Yes, I think we can just do that to keep it moving.

**Comment by bridgetburke** [comment]
I can work on the readme but should we just keep it in the design system repo? Do we need a "guides" folder or something separate?
